language: node_js
node_js:
  - "4.1"
os:
  - linux
script: node_modules/karma/bin/karma start karma.conf.js --single-run
before_install:
  - export CHROME_BIN=chromium-browser
  - export FIREFOX_BIN=firefox
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install
after_script: node_modules/grunt-cli/bin/grunt coverage
notifications:
  slack: mtr-design:8Hj8yAQDcHqPZKpylxbalk9K